-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-uw_campaigns-cleanup.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  uw_campaigns ALTER campaign_enabled TYPE SMALLINT;
ALTER TABLE  uw_campaigns ALTER campaign_enabled
SET  DEFAULT 0;