-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/uw_campaigns (
  campaign_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  campaign_name VARCHAR(255) NOT NULL,
  campaign_enabled SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX uw_campaigns_name ON /*_*/uw_campaigns (campaign_name);

CREATE INDEX uw_campaigns_enabled ON /*_*/uw_campaigns (campaign_enabled, campaign_id);
