-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-uw_campaigns-cleanup.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/uw_campaigns
CHANGE  campaign_id campaign_id INT AUTO_INCREMENT NOT NULL,
CHANGE  campaign_enabled campaign_enabled TINYINT(1) DEFAULT 0 NOT NULL;