-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: /var/www/wiki/mediawiki/extensions/UploadWizard/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/uw_campaigns (
  campaign_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  campaign_name VARCHAR(255) NOT NULL,
  campaign_enabled INT DEFAULT 0 NOT NULL,
  UNIQUE INDEX uw_campaigns_name (campaign_name),
  INDEX uw_campaigns_enabled (campaign_enabled, campaign_id),
  PRIMARY KEY(campaign_id)
) /*$wgDBTableOptions*/;
